server:
  port: 7777
  ssl:
    key-alias: python
    key-store: classpath:java.jks
    key-store-type: JKS
    key-store-password: veera123

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Database related details.
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hrms}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
      database: POSTGRESQL
      show-sql: true
      # set generate-ddl as false before pushing to production
      generate-ddl: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      properties:
        hibernate:
          default_schema: veera
